# Generated by Django 3.0.3 on 2020-04-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCorrespondence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receiving', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема обращения')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('message', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'received'), (1, 'answered')], default=0, verbose_name='Статус обращения')),
            ],
            options={
                'verbose_name': 'Обращение пользователя',
                'verbose_name_plural': 'Обращения пользователей',
            },
        ),
    ]
