# Generated by Django 3.0.3 on 2020-02-19 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrolled',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in_flow', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='homework',
            name='course_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='course.CourseFlows', verbose_name='Поток курса'),
        ),
        migrations.AddField(
            model_name='courselecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='course.Course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courseflowtimetable',
            name='course_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseflow_timetable', to='course.CourseFlows', verbose_name='Поток курса'),
        ),
        migrations.AddField(
            model_name='courseflowtimetable',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseflow_timetable', to='course.CourseLecture', verbose_name='Номер занятия'),
        ),
        migrations.AddField(
            model_name='courseflowtimetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='courseflows',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_flows', to='course.Course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courseflows',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_flows', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='course.CourseCategory', verbose_name='Категория'),
        ),
    ]
