# Generated by Django 3.0.3 on 2020-04-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200220_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='main_img',
        ),
    ]
