# Generated by Django 3.0.3 on 2020-04-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_studentshomework_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentshomework',
            name='content',
            field=models.TextField(blank=True, default='Прикрепите ссылку на репозиторий', max_length=300, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='studentshomework',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не сдано'), (1, 'На проверке'), (2, 'Отправлено на доработку'), (3, 'Сдано')], default=0, verbose_name='Статус работы'),
        ),
    ]
