# Generated by Django 3.0.3 on 2020-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
